### ISSUE TITLE
Polling vs subscription events

### ISSUE THREAD

**Issue by yousefamar** [me-box/databox-export-service#6]
I'm currently writing "front-end" export-service code for the Databox libs, and was just wondering a few things.

- Is polling for responses the final way it's going to be? Or will we at some point also allow `databox-store-blob`-like WebSocket subscription events? During the platform talk, I think somebody mentioned that there may be a store sitting in front the export service to hold responses. I personally think it's better if the export service itself is sort of a pseudostore, in the sense that it may replicate store APIs (e.g. WebSocket subscription events). Seems like there are at least 3 ways we're envisioning this, so I just wanted to make sure what we're aiming at.

- Is it safe to allow apps to set IDs for export requests? (e.g. what if one app sets stupid IDs and collides with another, or a different app starts enumerating IDs to try and steal another app's responses?) I think having the response to an export request include an unguessable UUID — which you already have — is an elegant way to do it, and that that is more than enough, so allowing apps to set IDs themselves wouldn't be necessary. (Btw, it's also possible to have app "sessions" by using the macaroons kind of like cookies since they each also contain unique IDs).

- Assuming the answer to the first point is yes, and the answer to the second is no, don't we need to have export requests be different from response polling requests? (i.e. two different API endpoints?) E.g. if an app wants to export two payloads to the same destination, and by the time it wants to export the second, the first hasn't cleared the queue yet, then it would have no way to push the second payload since the export service would interpret the request as a response poll for the first payload, right? I can see how giving each payload export its own ID would solve this, but then see point 2.

All thoughts and input appreciated a usual!

**Comment by sevenEng** [comment]
So for now, all the UUIDs assigned to requests are all generated centrally by the export service, and the service sees requests differently (*new export request vs polling*) based on the `id` field of a request (*empty string vs recognized id respectively*).

If an app wants to export two payloads to the same destination, it could generate this new request with an empty `id` filed, and the export-service will treat this as a new request and push it to the queue, no matter how many requests of the same app has already had in queue (*possible attack surface here, i.e. overflow the queue, maybe give a quantum to each individual client, by app `session`?*). I might not have made this clear in the [README.md](https://github.com/me-box/databox-export-service/blob/master/README.md#api), but concerning the use case mentioned in point 3, there should be no problem of achieving this (*or is the model a little wired for the developers in your opinions? open to discussion*)

And in terms of point 1, I'm not sure if I will have time to implement the WebSocket subscription style before the end March release, but in my mind it will definitely be there eventually. I prefer the pseudo-store style too. But I had this discussion about `bridge` component with mort and Hamed last week, and I'm afraid the priority before release will have to go to that one. :disappointed:

**Comment by yousefamar** [comment]
Ah I see, so the first request doesn't include an ID. So correct me if I'm wrong, this would be the client-side flow, right?

1. POST export-service/export `{dest: 'example.com', data: {foo: bar}}`
2. Response: `{ id: '123e4567-e89b-12d3-a456-426655440000', state: 'Pending' }`
3. While state not 'Finished'
  a. POST export-service/export `{ id: '123e4567-e89b-12d3-a456-426655440000' }`
  b. Response: `{ id: '123e4567-e89b-12d3-a456-426655440000', state: 'Processing' }`
  c. Some delay
4. Response: `{ id: '123e4567-e89b-12d3-a456-426655440000', state: 'Finished', response: { some: 'response' } }`

If we end up having some time, I can give the WebSocket thing a go if you don't mind. I was looking at some OCaml WebSocket libs and I could do a quick port of what's in store-blob.

I'm less concerned about developer comfort (either way it will be wrapped up in libraries) and more about the SOSP evaluation. I think the export throughput will suffer if badly designed apps are DDOSing the export service for responses. :P On the other hand, apps that delay between polling will have worse performance (time-to-availability and all that) if they rely on speed of response.

So I think event-driven notifications might be worth having across the board for SOSP rather than the March release.

**Comment by sevenEng** [comment]
Yes, the client-side flow is pretty much like what you described except that for the very first step, it would be something like: `{id: '', uri:'example.com', data:{foo: bar}}`, as we will always have the `id` field, but it's an empty string when submitting a new request.

And by all means have a go at the WS thing if you have time and interest :)

**Comment by cgreenhalgh** [comment]
alternatively you could add some minimal support for long polling, e.g. if the post has an id and optionally a state then the export service returns immediately only if the current state has changed; otherwise it delays on a condition variable or equivalent with some timeout (either a default or an extra parameter in the request) which will get signalled then the state changes.

**Comment by sevenEng** [comment]
Thanks @cgreenhalgh for the suggestion.

I've just added [a new branch](https://github.com/me-box/databox-export-service/tree/long-polling) which contains a long-polling version endpoint, with `/lp/export` as the query path.

Basically, if the request state is not `Finished`, the server will hang the client request on a conditioanl variable. At the worker side, each export request state change will trigger a signal to the corresponding condition variable. While the client waits on it, there is also a timer, timeout could also end the polling request: https://github.com/me-box/databox-export-service/blob/long-polling/src/export.ml#L165, well, *not sure if 5 seconds is ok for the timeout span*.
