### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox-export-service#8]
Hi 

The image for the export service is over 600 MB is their anything we can do to make it smaller?

Cheers

Tosh

**Comment by sevenEng** [comment]
While building one of the base images, [a big directory got cloned in](https://github.com/ocaml/opam-dockerfiles/blob/alpine_ocaml-4.04.0/Dockerfile#L20), which is approximately 160M. We could get rid of this by building our own customized base image. Is this cut in size enough? How big a image we are hoping for here?

**Comment by Toshbrown** [comment]
Smaller the better, we are going to have 50 odd people pulling this multiple times. Don't waste to much time on this but it would be good if it was smaller. Just did a quick $du -h -d 1

     412.1M	./.opam
     34.9M	./databox-export-service
     4.0K	        ./.omake
     163.7M	./opam-repository
     4.0K	        ./.ssh
     610.7M	.

Do you need the .opam and opam-repository dirs after it's compiled? If not removing them would help a lot. 

cheers

Tosh
